### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ed-biz23** [LandGrey/abuse-ssl-bypass-waf#1]
Hi, I'm receiving this following error, while running on windows 10 and pyhton 3.6. Thanks in advance.
[+] Target: https://www.nakedcph.com/ is alive
[+] Testing Web Server Supported SSL/TLS Ciphers ...
[-] No SSL/TLS Ciphers of target supported
[+] Request-1:https://www.nakedcph.com/  Request-2:https://www.nakedcph.com//?Lid=1008610086
[!] Response-1 length:[125262]  !=  Response-2 length:[125282]
[+] Now Request: https://www.nakedcph.com//?Lid=1%27or%271%27=%271..%2F..%2F..%2Fetc%2Fpasswd
Traceback (most recent call last):
  File "abuse-ssl-bypass-waf.py", line 154, in <module>
    bypass_testing(int(str(args.thread)))
  File "abuse-ssl-bypass-waf.py", line 124, in bypass_testing
    base_cipher_length = dict(cipher_content_length[0]).values()[0]
IndexError: list index out of range

**Comment by LandGrey** [comment]
Please using python 2 not python 3 and target not add "/", using "https://www.nakedcph.com" not "https://www.nakedcph.com/"
