### ISSUE TITLE
Error start script

### ISSUE THREAD

**Issue by reactiver001** [LandGrey/abuse-ssl-bypass-waf#2]
Hello i have this erro now .its possible help me to solve this ?
thanks 

Traceback (most recent call last):
  File "abuse-ssl-bypass-waf.py", line 167, in <module>
    bypass_testing(int(str(args.thread)))
  File "abuse-ssl-bypass-waf.py", line 101, in bypass_testing
    if is_alive():
  File "abuse-ssl-bypass-waf.py", line 27, in is_alive
    response = curl_request(target_handle(target), alive_command)
  File "abuse-ssl-bypass-waf.py", line 40, in curl_request
    execute = subprocess.Popen(command, shell=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by LandGrey** [comment]
there is `/usr/bin/curl` exists on your pc disk path? 

if not, modify `config.py` file line 42, write your `curl` file path.

**Comment by DeserranoJorden** [comment]
Having the same error here.
It's not because of the curl path.

**Comment by LandGrey** [comment]
> Having the same error here.
> It's not because of the curl path.

what's your command line and operator system ?

**Comment by DeserranoJorden** [comment]
I'm just trying the default command: 
`python abuse-ssl-bypass-waf.py -target https://api.example.com`

python version: 
`Python 2.7.18`

OS:
`5.8.0-kali2-amd64`

**Comment by DeserranoJorden** [comment]
Found the issue, it's the SSLscan path that was incorrect. 
Changed config.py to /usr/bin/sslscan.

**Comment by LandGrey** [comment]
> Found the issue, it's the SSLscan path that was incorrect.
> Changed config.py to /usr/bin/sslscan.

ok
